ConsumptionSaving/ConsMedModel.py
ConsumptionSaving/ConsPersistentShockModel.py
ConsumptionSaving/ConsumerParameters.py
HARKinterpolation.py

New attempt at pr/63, following GitHub workflow this time.

Medical shocks model

---

ConsumptionSaving/Demo.py

Tiny change to the HARKDemo implementing the change we agreed to in John's PR for the demo.
I'm issuing this as a new pull request because I do not have write access to John's repo, so I cannot change anything in the original PR
Assigning this to Matt because I can't assign it to John (I think because he doesn't have write access?) 
Should be very quick to merge in, I think....

Incorporated Johns comments about income_change

---

HARKcore.py

The solve method of AgentType now has an optional argument named verbose
(default False).  When True, solve displays progress of the solution
method (timing, convergence progress) after each cycle of periods.  Also
eliminated AgentType.isSameThing (now incorporated into solveAgent),
which Alex in particular hated.
New option is useful for testing infinite horizon models that a) take a
while to solve and/or b) don't necessarily converge because it's still
in development.  I often found myself adding lines like this anyway,
then deleting them before a commit; this makes testing easier.

Added verbose option to AgentType.solve

---

ConsumptionSaving/Demo.py
HARKutilities.py

Added a new argument to plotFuncs in HARKutilities.py so that keywords can be passed to plt.legend, if desired.  Also, not coincidentally, added legends to the figures produced by ConsumptionSaving/Demo.py

Legend in figures produced by plotFuncs

---

HARKinterpolation.py

Trivial addition to HARKinterpolation.py: ConstantFunction.  For representing functions that return the same value no matter what the
input (or how many inputs).  Yes, this is actually useful.

Added class ConstantFunction

---

HARKutilities.py

approxLognormal previously didn't work properly at very extreme inputs.
For example, trying approxLognormal(N=20,mu=-26,sigma=15) results in
many of the discrete values being 0.  In some cases, all but the top
point were 0.  This commit fixes this issue by adding an alternate
version for extremely low shocks.  The math has been simplified a bit,
and a typo in the docstring removed.

Fix to approxLognormal

---

HARKinterpolation.py

LinearInterp was previously mostly an extension of
scipy.interpolate.UnivariateSpline.  It has now been rewritten as a
fully custom class for HARK.  This was done because UnivariateSpline
uses 6-7x more memory than is necessary.  This is not a problem in
isolation, but can lead to memory constraints being binding in very
large models-- those with tens of thousands of LinearInterps.
All code runs identically as before these changes.  Old version remains
as LinearInterpOLD, for testing.  Should be deleted.  Some applications
run 5% faster, others are up to 14% slower than before.  We can fix
speed later by adding an option to the class that makes it use 50% more
memory.
Also fixed all classes where distance_criteria was not a static
attribute.

Rewrote LinearInterp from scratch

---

HARKutilities.py

makeTauchenAR1 discretizes an AR1 process

Adds new function makeTauchenAR1

---

README.md

Update README.md 
- links to docs added
- Markdown for titling sections added
- horizontal lines removed now that titles exist
- Adds links to the table of contents
^^ Overall makes readme more readable.

Updates formatting on README.md

---

.zenodo.json

Zenodo metadata file listing:
- title
- creators
- access_right
- license
- upload_type
- related_identifiers

Adding Zenodo metadata file

---

cstwMPC/Examples/Saving-VS-Uncertainty/PermShocksAggSaving.py
cstwMPC/Examples/Saving-VS-Uncertainty/README.md
cstwMPC/Examples/Saving-VS-Uncertainty/SetupParamsCSTWUncert.py
cstwMPC/Examples/Saving-VS-Uncertainty/TranShocksAggSaving.py

@llorracc  code is to calculate the relationship between aggregate saving rate and the degree of uncertainty.

Add Example Code and Edit Readme

---

cstwMPC/Examples/Saving-VS-Uncertainty/PermShocksAggSaving.py
cstwMPC/Examples/Saving-VS-Uncertainty/README.md
cstwMPC/Examples/Saving-VS-Uncertainty/SetupParamsCSTWUncert.py
cstwMPC/Examples/Saving-VS-Uncertainty/TranShocksAggSaving.py

The code is for a small sample that calculates the relationship between aggregate uncertainty and the degree of uncertainty. The original code has errors accessing directories above. This new version fixed the problem. @llorracc

Fixing errors in the small example that calculates the relationship between the aggregate saving rate and the degree of uncertainty

---

cstwMPC/cstwMPC.py

Matt,
I've made a small change to cstwMPC.py to add a statement:
if __name__ == '__main__':
at the start of the part of the file where it actually begins doing stuff (as supposed to defining stuff). Obviously I've also indented all the code below that line.
Do you know of a reason not to do this? I sometimes call cstwMPC in other code, so need this there to load the relevant objects without wasting time running all the code.
Edmund

Add if __name__ == '__main__' statement

---

Demos/ConsIndShockModel_Try-Alternative-Parameter-Values.py
HARKparallel.py
HARKutilities.py

* Fix error message for missing parallel imports
* Show a more descriptive error on missing Tkinter
* Remove obsolete link 
Commits by @jasonaowen.

Clean up imports, improve error message, and remove obsolete link

---

HARK/ConsumptionSaving/TractableBufferStockModel.py

Adds explanatory info about a few obscure variables, and provides a link to the TractableBufferStock lecture notes

Improve documentation for TBS per issues #36 and #183

---

HARK/interpolation.py

Solves #156 
Also checked the trilinear and quadlinear interpolation methods. They are correct.

BilinearInterpBug

---

HARK/interpolation.py
HARK/tests/test_discrete.py

This PR supercedes #209 and was made while adding an extra commit to that.  See that thread for history and discussion.

Merge PKM's basic discrete choice tools

---

HARK/ConsumptionSaving/ConsIndShockModel.py

Alright, so this is basically a new attempt at the changes that can be seen on the Fix-Impatience-Tests branch. The changes were previously merged into master, but caused some problems, see #175.
I need to verify that the problems @npalmer-professional discovered have not reappeared.
@llorracc I'd appreciate your input here; did you want me to do anything further than what was in the Fix-Impatience-Tests branch, or is this what you had in mind? Notice, I did not copy/paste the lines, as I wanted to avoid introducing the same white space issues.

Improvements to checkConditions that were reverted, ref #175.

---

CONTRIBUTING.md

CONTRIBUTING.md files are a best practice for open source software projects.  This is a bit bare bones but it will eventually grow to contain more helpful information (you can take a look at @nayafia's excellent [contributing template project](https://github.com/nayafia/contributing-template) to get a sense of what it will eventually contain).  
Chris, Matt and anyone else who's interested - please feel free to make additions or suggest edits if you like.  I'm particularly concerned that I may have described the items in the "few key areas we'd especially like help with" section incorrectly.

Add CONTRIBUTING.md file to HARK repository

---

HARK/dcegm.py

As per our discussion, these were some of the small things Matt had spotted. @shaunagm

Update some text in dcegm

---

CHANGES.md
MANIFEST.in
setup.py

This PR makes the necessary updates to release our newest version.

Prepare release 0.10.0.dev1

---

HARK/ConsumptionSaving/ConsIndShockModel.py

Add a comment to the construction of aNrmNow

---

README.md

Partial update to README for PyCon

---

.gitignore
Testing/Comparison_UnitTests.py
Testing/ModelTesting.py

Also added venv and vscode settings.json to .gitignore

Linted Comparison and Model Tests

---

HARK/core.py

Linted the Core.py file to make some changes

---

README.md

Add "Learning HARK" section to README

---

HARK/tests/test_validators.py
HARK/validators.py
requirements.txt
setup.py

This prototypes a decorator-based approach to help address some issues noted in https://github.com/econ-ark/HARK/issues/190
Decorators for all kinds of common cases could be introduced to validate arguments

Add non_empty argument validator

---

CHANGES.md
HARK/__init__.py
setup.py

Adds release notes & bumps version #.

Prepare release 0.10.0.dev3

---

HARK/ConsumptionSaving/ConsIndShockModel.cl
HARK/ConsumptionSaving/ConsIndShockOpenCL.py
HARK/tests/OpenCLtest.py

For the SciPy sprint, put the OpenCL version of ConsIndShock into the master branch

Add ConsIndShockOpenCL to ConsumptionSaving

---

HARK/ConsumptionSaving/ConsAggShockModel.py

Missed a required fix in ConsAggShockModel like the others

Also fix ConsAggShockModel

---

.gitmodules
.readthedocs.yml
Documentation/index.rst
Documentation/notebooks/README.rst
Documentation/submodules/README.rst

An example is online here: https://test-hark.readthedocs.io/en/add-submodule/submodules/DemARK/notebooks/KinkedRconsumerType.html

Add a submodule of DemARK and include a notebook in the doc build for it

---

Documentation/index.rst

I imagine some of these should not be added,
but I'm not sure which ones :)

This adds all the Python classes to the Sphinx docs

---

HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/ConsumerParameters.py

Finished issue #103 with helps and feedback from Matthew.

Attempt on Issue #103

---

README.md

fixing README instructions to resolve #396

 #396 : fixing typo in README: hNm -> hNrm

---

README.md

readme: update notebook refs to econ-ark/DemARK

---

HARK/ConsumptionSaving/ConsIndShockModel.py

priont -> print

---

HARK/cstwMPC/cstwMPC.py

Fixes https://github.com/llorracc/cstwMPC/issues/1

Inherit all attributes from Market Class in cstwMPC

---

HARK/estimation.py

Fixes the DemARK build and 0.10.3

fix slicing error in minimizeNelderMead

---

HARK/cstwMPC/cstwMPC.py

This should fix the problem here:
https://github.com/econ-ark/DemARK/issues/83

Fixing path to SetupParamsCSTW

---

CONTRIBUTING.md
doc/guides/contributing/issues.md

add guide to link fork

---

setup.cfg

move install_requires to option to fix build of `pip install git+https://github.com/econ-ark/HARK.git@master`

fix setup.cfg order

---

HARK/ConsumptionSaving/ConsIndShockModel.py

url -> self.url in checkConditions print logic. fixed #539

---

HARK/SolvingMicroDSOPs/Calibration/EstimationParameters.py

fixes https://github.com/econ-ark/HARK/issues/551

remove the quick fix from estimation parameters

---

.travis.yml

removing 2.7 from travis

---

HARK/ConsumptionSaving/ConsPrefShockModel.py

There are some breaking errors in ConsPrefShockModel that this PR fixes.

syntax and param dictionary fixes for ConsPrefShockModel

---

HARK/core.py

Addresses #575 
I've used getattr here.
For the sake of making more incremental changes, I'll save the proposal for the 'history' namespace fo a different PR
This is ready to merge, from my perspective.

replacing 'exec' statements with getattr/setattr

---

HARK/ConsumptionSaving/tests/test_ConsPrefShockModel.py

test for solution and simulation of ConsPrefShockModel

tests for ConsPrefShockModel, fixes #588

---

HARK/dcegm.py
HARK/estimation.py
HARK/interpolation.py
HARK/parallel.py

removes the other apologetic main methods from the HARK library files

remove other main() methods from HARK library files

---

examples/FashionVictim/FashionVictimModel.py

This example model was out of date with current HARK format; now fixed.  Also tweaked a few comments.

Fix small issues with FashionVictimModel

---

HARK/ConsumptionSaving/ConsAggShockModel.py
HARK/ConsumptionSaving/tests/test_SmallOpenEconomy.py
HARK/core.py

A test for the SmallOpenEconomy class.
In this PR, I've tried to write the test but could not get it to work.
I'll need to ask @mnwhite how to fix it in our weekly meeting if he doesn't respond before then.

SmallOpenEconomy test

---

examples/Gentle-Intro/Gentle-Intro-To-HARK.ipynb
examples/Gentle-Intro/Gentle-Intro-To-HARK.py

fixes https://github.com/econ-ark/HARK/issues/513

tqdm isn't required in the Gentle Intro notebook

---

.github/SUPPORT.md
README.md

fixes https://github.com/econ-ark/HARK/issues/375

fix up links in README

---

HARK/ConsumptionSaving/ConsIndShockModel.py

The new impatience to patience transition is missing a line of the perfect foresight checkRIC.

RIF -> RPF in PrefForesight checkRIC

---

Documentation/CHANGELOG.md

update CHANGELOG with #765 change

---

examples/Journeys/Journey 2 Engineering Background.ipynb

- [ N/A ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ N/A ] Updated documentation of features that add new functionality.
- [ N/A ] Update CHANGELOG.md with major/minor changes.
Fixes https://github.com/econ-ark/HARK/issues/778

fix links in journey 2

---

HARK/ConsumptionSaving/ConsGenIncProcessModel.py
HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/ConsMarkovModel.py
HARK/ConsumptionSaving/ConsMedModel.py
HARK/core.py

Fixes https://github.com/econ-ark/HARK/issues/816

Use a generic assignParameters for *Solvers

---

HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py

adding simulation test for ConsPortfolioModel

---

HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py

Tests for the values of particular transitions in ConsPortfolioModel

portfolio tests

---

Documentation/CHANGELOG.md
HARK/__init__.py
setup.cfg

PR to update changelog, __init__.py, and setup.cfg for 0.10.8 relese

Sb 0.10.8 release

---

examples/Journeys/Journey_1_PhD.ipynb

Documentation fixes to PhD Journey. Fixes #879

fixing image links, grammar, and some references to code in Phd Journey

---

HARK/ConsumptionSaving/ConsPortfolioModel.py

set 'ShareNow' properly in simBirth

---

HARK/ConsumptionSaving/ConsIndShockModel.py

Checks whether the conditions for the existence of `mNrmSS` and `mNrmTrg` are actually satisfied before attempting to find them.

Check conditions before finding mNrmSS and mNrmTrg

---

HARK/ConsumptionSaving/ConsIndShockModel.py

A _very small_ use of calcExpectations ( breaking down work for #893 into smaller, test-passing steps)

compute expected income in ConsIndShockModel with calcExpectations

---

Documentation/CHANGELOG.md
HARK/ConsumptionSaving/ConsAggShockModel.py
HARK/ConsumptionSaving/ConsGenIncProcessModel.py
HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/ConsMedModel.py
HARK/ConsumptionSaving/ConsPrefShockModel.py
HARK/distribution.py
HARK/tests/test_distribution.py

rename DiscreteDistribution.drawDiscrete -> draw . fixes #910

---

Documentation/CHANGELOG.md
HARK/core.py

- [x ] Updated documentation of features that add new functionality.

simulate() returns history. fixes #333

---

HARK/ConsumptionSaving/ConsAggShockModel.py
HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/ConsLaborModel.py
HARK/ConsumptionSaving/ConsMarkovModel.py
HARK/ConsumptionSaving/ConsPrefShockModel.py

Documents role of makeEulerErrorFunc

documented the role of makeEulerErrorFunc. Fixes #892

---

HARK/ConsumptionSaving/ConsIndShockModel.py

use calcExpectatiosn in checkConditions. Fixes #904

---

Documentation/CHANGELOG.md
HARK/ConsumptionSaving/ConsAggShockModel.py
HARK/ConsumptionSaving/ConsGenIncProcessModel.py
HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/ConsIndShockModelFast.py
HARK/ConsumptionSaving/ConsLaborModel.py
HARK/ConsumptionSaving/ConsMarkovModel.py
HARK/ConsumptionSaving/ConsMedModel.py
HARK/ConsumptionSaving/ConsPortfolioModel.py
HARK/ConsumptionSaving/ConsPrefShockModel.py
HARK/ConsumptionSaving/ConsRepAgentModel.py
HARK/ConsumptionSaving/tests/test_ConsAggShockModel.py
HARK/ConsumptionSaving/tests/test_ConsMarkovModel.py
HARK/ConsumptionSaving/tests/test_ConsRepAgentModel.py
HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
HARK/ConsumptionSaving/tests/test_modelcomparisons.py
HARK/tests/test_distribution.py

IncomeDstn -> IncShkDstn. Fixes #227

---

.github/workflows/coverage.yml
.github/workflows/hark.yml
README.md

implements https://github.com/econ-ark/HARK/issues/877, Codecov report is now created as part of our CI

Use Codecov to create a coverage report.

---

HARK/Calibration/Income/IncomeTools.py
HARK/datasets/SCF/WealthIncomeDist/SCFDistTools.py
HARK/datasets/cpi/us/CPITools.py
HARK/datasets/life_tables/us_ssa/SSATools.py
HARK/datasets/load_data.py
HARK/datasets/tests/test_load_data.py

implements https://github.com/econ-ark/HARK/issues/965

use HARK logging instead of warn

---

examples/ConsumptionSaving/example_ConsRepAgentModel.ipynb

The text in the rep agent example was copy-pasted from the medical shock model. It looks like some stuff got fixed, but I cleaned up the rest. Notebook should probably be run again by someone with the latest version of HARK installed locally. Only markdown cells changed on this commit. Fixes #964 
Nothing added to changes log, as this just fixes example documentation.

Update model text in rep agent model

---

HARK/ConsumptionSaving/ConsAggShockModel.py
HARK/ConsumptionSaving/ConsGenIncProcessModel.py
HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/ConsMarkovModel.py
HARK/ConsumptionSaving/ConsMedModel.py
HARK/ConsumptionSaving/ConsPrefShockModel.py
HARK/ConsumptionSaving/ConsRepAgentModel.py
HARK/ConsumptionSaving/TractableBufferStockModel.py
HARK/core.py
HARK/interpolation.py
HARK/simulation.py
HARK/tests/test_HARKutilities.py
HARK/tests/test_discrete.py
HARK/utilities.py
examples/Journeys/Journey_1_param.py
examples/Journeys/Quickstart_tutorial/Jounery_1_param.py
examples/LifecycleModel/EstimationParameters.py

closes https://github.com/econ-ark/HARK/issues/993

clean up future imports

---

HARK/ConsumptionSaving/ConsPortfolioModel.py

As part of his vision for the future of solvers, @llorracc asked me to store a few more objects in the solution class of the portfolio model, namely the grids and exact points used to calculate the end-of-period marginal value of resources. This PR adds those objects to the solution class.

Store more solution ingredients in `PortfolioSolution`

---

.gitignore
HARK/ConsumptionSaving/ConsIndShockModelFast.py
HARK/ConsumptionSaving/ConsRiskyContribModel.py
HARK/distribution.py
HARK/interpolation.py
HARK/utilities.py

These should be innocuous changes which can be merged into HARK master

---

Documentation/CHANGELOG.md
HARK/__init__.py
setup.cfg

This PR updates the version numbers for the 0.12.0 release

HARK 0.12.0 release commit

---

Documentation/CHANGELOG.md
HARK/ConsumptionSaving/ConsMarkovModel.py
HARK/ConsumptionSaving/tests/test_ConsMarkovModel.py

Fixing vFuncBool in ConsMarkov

---

HARK/ConsumptionSaving/ConsMarkovModel.py

- [x ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x ] Updated documentation of features that add new functionality.
- [ x] Update CHANGELOG.md with major/minor changes.

Fix vFuncBool in ConsMarkovModel

---

Documentation/reference/tools/utilities.rst

Fix tiny typo

---

Documentation/example_notebooks/ConsPortfolioModel.ipynb
Documentation/example_notebooks/example_ConsPortfolioModel.ipynb

examples_ConsPortfolioModel was an incorrect link.  Fixed.

Fix-ConsPortfolio-Model-Link

---

examples/ConsIndShockModel/Finite Cyclical Test.ipynb
examples/ConsIndShockModel/IndShockConsumerType.ipynb
examples/ConsIndShockModel/IndShockConsumerType.py
examples/ConsIndShockModel/KinkedRconsumerType.ipynb
examples/ConsIndShockModel/KinkedRconsumerType.py
examples/ConsIndShockModel/PerfForesightConsumerType.ipynb
examples/ConsIndShockModel/PerfForesightConsumerType.py

This PR fixes the typos in the examples of ConsIndShockModel. 

Fixes typos in the examples/ConsIndShockModel

---

examples/Journeys/Journey_1_PhD.ipynb

clarify that Y is a state in phd-journey

---

HARK/utilities.py

omit savefig metadata to improve version control

---

HARK/interpolation.py

This should fix the new test failures popping up in github actions.

Creating an ndarray from ragged nested sequences is deprecated

---

.github/workflows/documentation.yml

This PR adds an initial GitHub Actions workflow to render HARK's documentation. I then intend to tackle uploading to Pages and resolving the myriad warnings in follow-ups, this PR is just to act as a baseline stage.
cc: @MridulS
A

Create documentation workflow

---

.github/workflows/documentation.yml
Documentation/conf.py

This adds deployment of the current rendered HTML from Sphinx to GitHub Pages.
A

Deploy to GitHub Pages

---

Documentation/reference/tools/numba_tools.rst

This module was renamed in #1183.
A

Properly document ``HARK.numba_tools``

---

Documentation/_static/theme_overrides.css
Documentation/conf.py
requirements/dev.txt

Work is needed to e.g. make the table of contents work better.
A

Switch to ``pydata-sphinx-theme``

---

Documentation/conf.py

Add CNAME to host website under econ-ark.org

---

pyproject.toml

This should fix https://github.com/econ-ark/HARK/issues/1276

Use setuptools_scm to track data files

---

Documentation/conf.py

cc: @MridulS 
A simple PR, and an oversight from setting the favicon. (Sorry!)
A

Add logo to online documentation

---

.github/workflows/documentation.yml
Documentation/conf.py
pyproject.toml
requirements/dev.txt
requirements/doc.txt

cc: @MridulS 
This PR splits out development from documentation dependencies; categorises the extensions list; and adds two new extensions.
A

Preparatory configuration updates

---

.github/workflows/documentation.yml

cc: @MridulS
To speed up CI runs.
A

Build documentation in parallel

---

.github/workflows/execute-notebooks.yml
tools/nb_exec.py

cc: @MridulS
Follow-up from #1330. Several things weren't quite right -- I didn't quite do enough testing on the CI runners, which have different environments to my local computer.
Please could you check that ["Allow GitHub Actions to create and approve pull requests"](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#preventing-github-actions-from-creating-or-approving-pull-requests) is turned on in the repository settings?
* Add a scheduled cron job
* Only run this workflow on the master HARK repository, not forks
* Explicitly give the workflow permissions to open pull requests
* Install ``estimagic`` (required for ``LabeledModels.ipynb``)
* Ensure all paths are …

Fix ``nb_exec.py``

---

Documentation/overview/ARKitecture.md

Addresses the low-hanging fruit in #1352.
A

Improve ARKitecture

---

Documentation/CHANGELOG.md
HARK/__init__.py
pyproject.toml

This is just version number and date changes, will merge on my own.

Adjustments for 0.14.1 minor release

---

Documentation/guides/contributing.md

Builds on #1326
- Minor changes to make code more applicable across different operating systems
- Minor typo fixes
All this in addition to the fixes made by @AA-Turner

Update contributing guide

---

HARK/econforgeinterp.py
pyproject.toml

This fixes one of the failing tests, which simply has a typo.
There are still tests that fail on 3.11 but that I can not reproduce locally.

Model test bugfix

---

HARK/__init__.py
pyproject.toml

CHANGELOG changes were pushed directly to master branch. Packaged release has been tested. Release of version 0.15.0 is imminent.

Bump version to 0.15.0

---

Documentation/CHANGELOG.md
HARK/__init__.py
pyproject.toml
requirements/base.txt

The new minor release of HARK will happen as soon as tests for this branch run.

Version bump to 0.15.1

---

Documentation/overview/ARKitecture.md

A small PR to fix the issues that were created when sphinx updated to be slightly stricter in checking markdown documents.

removes broken footnote

---

binder/requirements.txt
examples/ConsNewKeynesianModel/KS-HARK-presentation.ipynb

and remove the pip install, it should be in the HARK binder setup not in a cell.

Add sequence_jacobian to requirements for binder 

---

examples/Journeys/Journey-Policymaker.ipynb

Commit 199b34c2e3ae191277b324811e17199f8742f0b1 renamed the transition matrices notebook. This PR adjusts sources to changes.

update transition matrices notebook reference

---

HARK/ConsumptionSaving/ConsNewKeynesianModel.py

Just wanted to give an example of how the functionality introduced in https://github.com/econ-ark/HARK/pull/1543 can be helpful. Here I am replacing two small bits of code in @wdu9 's Jacobian code.
This is not ground breaking work and might not even be worth merging, but it just makes the code marginally more readable, I think.

Use "from_solution" solves in NKAgent

---

.github/workflows/documentation.yml
.github/workflows/examples.yml
.github/workflows/execute-notebooks.yml
.github/workflows/hark.yml
.github/workflows/lint.yml
Documentation/CHANGELOG.md
pyproject.toml
requirements/base.txt

MAINT: Support python 3.13; remove numba, numpy upper pins

---

Documentation/CHANGELOG.md
HARK/Calibration/Income/IncomeProcesses.py
HARK/ConsumptionSaving/ConsIndShockModel.py
HARK/ConsumptionSaving/tests/test_ConsNewKeynesianModel.py
HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
HARK/ConsumptionSaving/tests/test_modelcomparisons.py
HARK/distributions/base.py
HARK/distributions/continuous.py
HARK/distributions/discrete.py
HARK/distributions/multivariate.py
HARK/distributions/utils.py

Alan rejiggered the contents of distribution.py, so I have recreated the changes from PR #1479 into this one. Committing and then will run tests.

Reproduce PR #1479

---

docs/CHANGELOG.md
pyproject.toml

This is the release prep PR for v0.16.1.

Bump version to 0.16.1, finalize changelog
