- ConsumptionSaving/ConsMarkovModel.py
- ConsumptionSaving/TractableBufferStockModel.py
Updated the Markov model to allow the survival probability LivPrb to
vary between discrete Markov states.  This is useful for having states
represent discrete health levels (so that someone in poor health is more
likely to die than someone in good health).
Moreover, it's a back-door route to do the Krussell-Smith model of
infinitely lived dynastic agents who occasionally change their discount
factor due to a generational change (DiscFac --> 1.0, LivPrb substitutes
for DiscFac).  Must turn off mortality in simulation for this to work.
> LivPrb can vary across Markov states

- HARKparallel.py
The demos for the Fed Board imported cstwMPC, which imported HARKParallel, which would not work on any machine that did not have joblib and dill installed.
We want the demos to work for anyone, so I modified HARKParallel to _try_ to import joblib and dill.  If it can't, it will instead define the functions it tried to import to raise appropriate error messages
> Robust hark parallel

- HARKinterpolation.py
Changed one line of code in HARKinterpolation.py, in  the calculation of x_temp in the _evalOrDer method of LinearInterp.  Previous code didn't work.
This should be a super simple PR.  Let me know if not.
> Tiny fix to decay interpolation in linear interpolation 

- ConsumptionSaving/ConsRepAgentModel.py
Even though it's a straight up contradiction, I've added two simple representative agent models in a new module.  These were written for the cAndCwithStickyE paper, which will soon be added to main HARK as an additional paper example (the version in the repo now is old and broken and was only meant to be added temporarily).
> Added representative agent models

- ConsumptionSaving/ConsIndShockModel-Demos/Try-Alternative-Parameter-Values.py
- ConsumptionSaving/ConsRepAgentModel.py
- ConsumptionSaving/Demos/Fagereng_demo.py
- ConsumptionSaving/RepAgentModel.py
- HARKinterpolation.py
- HARKutilities.py
- cAndCwithStickyE/StickyE_NO_MARKOV.py
In support of finding dependencies and transitive dependencies that make packaging HARK more difficult, remove some of the import statements that bring in dependencies that are not used in the code, as detected by flake8:
```bash
git ls-files '*.py' | xargs flake8 --select=F401
```
In particular, some of the apparently-unused imports not removed are due to usages flake8 can't detect, such as the fact that the HARKutilities.warnings import has side effects, or the `exec()` use of `copy.copy`.
Issue #85 Add setup.py so module can be installed
> Remove (some) unused imports

- requirements.txt
scipy is required in HARK (.utilities) so it should be in requirements.txt
> Add scipy to requirements.txt

- .travis.yml
- HARK/tests/test_initial.py
- requirements.txt
Since I don't have the `econ-ark` keys, I need someone to log in to https://travis-ci.org/ and click the button to enable github integration for the travis-ci service.
I put in the simplest test module from `Testing` just to show how it works. If you want this, then I'd hope it could be merged with only these basic tests, and then I can add the rest later. I had problems running the some of the other test modules (kind of shows why we need this), but I'd rather use this infrastructure to add tests for some of the discrete choice functions that I'm using in the other PRs, and make PRs for those. Then I can come back to fix some of the problems with the other test modules.
I have never used travis for python projects, so it took a bit of experimenting, but a `tests` folder with an …
> Setup basic travis support.

- HARK/FashionVictim/FashionVictimModel.py
This is a tiny fix needed to bring FashionVictim up to date with the changes that happened when HARK became pip-installable.  No longer right to say "from . import" -- instead it need to be "from HARK.FashionVictim import".
> Update FashionVictim to work as HARK package

- HARK/interpolation.py
- HARK/tests/test_discrete.py
It works, and I use it in #200 #201 #206 , and given the discussion in #206 it seems that @mnwhite also do stuff with discrete choices. I'd prefer to have it somewhere in HARK instead of repeating it in the modules three times.
How does the name work for you @mnwhite ? I just chose something, but I'm actually quite indifferent. It could have `Upper` in it as well I guess. Is it a problem that it also calculates the policies?
I have some tests as well, one which can be seen at https://github.com/pkofod/HARK/pull/3 , that I can add after #208 is (potentially) merged.
> Add calcLogSum, calcChoiceProbs and combined calcLogSumChoiceProbs to HARK.interpolation.

- HARK/ConsumptionSaving/ConsIndShockModel.py
@mnwhite this seems to be wrong, right? I don't see any `self.constructIncomeProcess`-ish statements, so it appears that the mean one log-normal equiprobably version is hard-coded. Correct?
I think we should remove the statement unless I missed something in the code, and if it's a *planned* feature, let's just open an issue.
> Remove incorrect statement in updateIncomeProcess

- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
The MPC is calculated and stored as an attribute (MPCnow) in some models, but this was omitted in ConsGenIncProcessModel.  As it turns out, this functionality is necessary for an exercise/notebook that is being prepared for NBER SI.
> Add MPC to simulation in ConsGenIncProcessModel

- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/interpolation.py
Tim Munday's nan_bool feature on LowerEnvelope (etc), which had been merged into master by me, worked on Py3 but not Py2.  Trying to fix by rearranging order of inputs failed, so this PR reverts that PR.
We still do want nan_bool, but will need to change the syntax of LowerEnvelope (etc) *and everywhere it's implemented* from 
`def __init__(self,*functions):`
to
`def __init__(self,functions):`
This only requires throwing brackets around all of the argument lists where we make a LowerEnvelope (etc), but we need to be thorough.  Should also discuss how to handle the fact that we're changing syntax of a long-standing function class, so *other people*'s code will break next time they update HARK, if they were using this.
> Undo nan_bool merge

- HARK/core.py
@llorracc this should do the job. It ignores the floating point exceptions. Currently we only warn anyway, so it's not like we're handling it.
The exceptions aren't really errors either as numpy calls them. They're well-defined operations that give useful answers. Things such as `-1/-np.inf` gives `0`. This is very useful in DCEGM to interpolate from the lowest value to the first values of the resource grid that is not `0`. It could be special handled, but this is implemented all the way down to the hardware level, so I don't see why we shouldn't just use it.
> set numpy floating point error level to ignore.

- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/ConsumerParameters.py
Four parameters that govern how CobbDouglasEconomy.updateAFunc works
were defined locally, within the method, but are now attributes to be
assigned at init (or at least before the user tries to solve):
- update_weight --> DampingFac, now defined complementarily
- verbose --> verbose
- discard_periods --> T_discard
- max_loops --> max_loops
To prevent this from being a breaking change, init method writes old
hardcoded values if omitted from passed inputs.  This will be improved
with a warning later.
Untested, as it turns out Anaconda3 is incorrectly installed on this
computer.
> Changed hardcoded updateAFunc parameters into proper parameters

- .travis.yml
- requirements.txt
- setup.cfg
This PR adds Flake8 tests to Travis, and also install Flake8 with the requirements so people can lint the codebase locally.  I've also added it to the config file and made an initial adjustment of setting our max line length to 120.
> Add Flake8 to requirements, setup, and travis

- README.md
Modify file links to use [relative links][1] rather than absolute ones, because the CONTRIBUTING.md link was directing to a branch that has since been deleted.
Also hyperlink to code files listed at the end of the README, and delete links to files that no longer exist.
[1]: https://help.github.com/en/articles/about-readmes#relative-links-and-image-paths-in-readme-files
> Modify hyperlinks to use relative links feature from GitHub

- HARK/dcegm.py
it still gets
`dcegm.py:155:25: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dcegm.py:161:26: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dcegm.py:175:50: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
`
> Simple lint edits commits for dcegm.py

- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
Just linted another file! I also missed adding a return to the def in ConsAggShockModel.py when I switched from a lambda so I fixed that as well.
> Linting ConsGenInc~.py

- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/ConsMarkovModel.py
- HARK/ConsumptionSaving/ConsMedModel.py
- HARK/ConsumptionSaving/ConsPrefShockModel.py
- HARK/ConsumptionSaving/ConsRepAgentModel.py
IndShockConsumerType.__init__ was calling its checkConditions method, but this caused many subclasses to fail, as their checkConditions method either throws a notImplementedError or runs into an attribute error.
CDC wants checkConditions called automatically, so this is now done in preSolve().  All subclasses have had a trivial preSolve method added, which only calls updateSolutionTerminal.
> Moved checkConditions out of init

- HARK/core.py
Delinting at PyCon created a typo in the argument list for Market, now fixed.  This addresses the same issue as just-closed PR from CDC #285
> Fix typo in Market.__init__

- HARK/core.py
- HARK/parallel.py
> Fixes multithreading problem from ipython kernel

- HARK/core.py
Docstring doesn't match behavior.
> Update docstring of simDeath() in core.

- HARK/core.py
- HARK/tests/test_simulate.py
So, I'm just PRing some minor things I'm finding on my way to matching a portfolio share. I've actually thought about this before (last fall!) but you quickly forget these things/learn to live with them.
Essentially, before this PR, if you tried to `simulate()`, but you hadn't `solve()`ed, you would just get a message stating that
```
AttributeError: 'IndShockConsumerType' object has no attribute 'solution'.
```
I'm not sure that all new users, and maybe new python users, would immediately know why this is. We probably know what went wrong though! They didn't `solve`.
Added a simple test to verify that this is actually thrown by initializing an `IndShockConsumerType`, setting it up, running simulate, but without having solved it.
> Throw an Exception if model has not been solved prior to simulate'ing

- setup.py
Fixes issue #279.  Removes line `include_package_data=True,` in `setup.py`, an alternative method for including data files which wasn't working due to the relevant lines being commented out in `manifest.in and which was conflicting with the more precise specification of which files we wanted.  Also fixes the path for the `SCFdata.csv` file, which pointed to the wrong directory.
> Fix datafile packaging issue

- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/ConsIndShockModel.py
@pkofod's commit on June 20 broke the KrusellSmith notebook among others -- this PR removes the lines that caused the problems (and also the functionality that they were intended to accomplish).  We need to revisit.
> Undo June 20 commit to preSolve AgentType because it breaks things

- HARK/ConsumptionSaving/ConsPortfolioModel.py
Fix #389 
So there were some leftover lines from a different way of constructing the re-curving value function interpolation.
A thing I noticed while trying this out to be sure it worked. If you set the probability to 0.5 and look at the share of periods where the agents can adjust, it'll be closer to 0.6 than 0.5. It could maybe be interesting to ask students to calculate the empirical share, and comment. (The answer is that when a new agent is replacing an old one whose lifecycle ended or who died, a new agent will always get the choice of their initial portfolio which implies a slightly higher "can adjust" ratio than 0.5).
> Fix AdjustPrb for discrete portfolio choice.

- HARK/core.py
- HARK/tests/test_core.py
Started adding tests for the classes and functions in core.py 
Made some changes to the core.py itself as I found a couple of bugs in the code.
- a logic bug(typo) in distance metric https://github.com/econ-ark/HARK/commit/9563bcf546cb8ff6fea152b381c68a957b7566d9
- a statement which will throw an error, `thing_A.shape - thing_B.shape` won't work as both are tuples, changed it by using flatten and then comparing lengths. https://github.com/econ-ark/HARK/commit/24dea3eccd022663de221724a6d4f031244d64a5
- removed certain instances of `exec()` and `eval()` as there are other ways of doing the same thing
@mnwhite @llorracc
> Add base tests for core.HARKobject, core.distanceMetric, core.AgentType

- README.md
`conda install econ-ark` only works if the user has conda-forge as the default conda channel.  Replaced it with `conda install -c conda-forge econ-ark` which will work generically.
> Robustify conda installation command

- Documentation/api.rst
The Python API readthedocs have too many entries for the specific models implemented in HARK (such as BayerLuetticke).
This PR removes all of those entries from the API documentation.
In the project meeting, we discussed remove everything below two layers in the module hierarchy (i.e., only entries of the form `HARK.*`). But since `HARK.BayerLuetticke` is a directory, not a module, the corresponding "API Doc" for this entry was empty and so is nonsensical.
The current implementation cleans up the ReadTheDocs to make them more usable.
It punts on the question of how to document the Models.
> removing Model directories from the API documentation

- HARK/utilities.py
Added two lines to utilities.getPercentiles to correctly handle case when data has size 0 or 1: return NaN vector of same size as requested percentiles of data.  That is, there is no such thing as "percentiles" of an empty dataset or a singleton.  This can come up when simulated or empirical moments are calculated, but no observations qualify.
> Tiny fix to getPercentiles

- requirements.txt
The most recent `nbsphinx` release 0.5.0 is incompatible with Sphinx v1.6.7 and is breaking our ReadTheDocs build.
https://github.com/econ-ark/HARK/issues/409#issuecomment-558672732
This PR fixes `nbsphinx` to the previous version to try to get the build going again.
> fix nbsphinx version to 0.4.3 to get compatibility with Sphinx v.1.6.7

- .github/workflows/hark.yml
Github introduced Actions which can be used like Travis/Azure for testing code, I have added support for py 3.6 and 3.7 in MacOS, Windows and Ubuntu. [This is much faster than current Travis setup]
This will look like https://github.com/MridulS/HARK/runs/392930709
> use github actions for testing MacOS, Windows and Ubuntu

- HARK/core.py
- HARK/cstwMPC/cstwMPC.py
- HARK/interpolation.py
- HARK/parallel.py
- HARK/tests/OpenCLtest.py
Instances of time.clock in consumptionsaving is removed in https://github.com/econ-ark/HARK/pull/455
> time.clock is removed from py3.8

- Documentation/conf.py
- requirements.txt
- setup.py
Addresses #473
`numpydoc` is not a necessary dependency; its functionality is now part of `sphinx.ext.napoleon`
> Remove numpydoc dependency

- Documentation/introduction.md
- Documentation/list-of-files.md
Change RTD link to manual to point to http://econ-ark.github.io/HARK/Documentation/HARKmanual/
> RTD point to gh manual

- HARK/ConsumptionSaving/ConsIndShockModel.py
See #534 
In order to save on code duplication, I've functionalized out each condition from checkConditions.
> Functionalize out each condition from checkConditions

- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
- HARK/ConsumptionSaving/tests/test_PerfForesightConsumerType.py
…, based on ConsPortfolioModel Documentation DemARK
part of #543
> adding test_ConsPortfolioModel

- HARK/parallel.py
parallelNelderMead still refers to maxcores in its code, but the parameter is maxthreads; not sure how this even worked before.  Now fixed.
> Fix typo in parallel.py

- HARK/ConsumptionSaving/tests/test_ConsAggShockModel.py
- HARK/distribution.py
These two lines can be run outside the loop, avoiding an error when N<events.size and also saving time.
The error occurs when j=0 and event_draws is empty (X[event_draws] throws an error).
> Bug fix to drawDiscrete

- HARK/ConsumptionSaving/ConsPortfolioModel.py
This implements the solution proposed by @mnwhite  in #741 for dealing with cases where the agent wants to hold less than a 0% share of the risky asset.
I did some testing and it seems to be well behaved. The approach assumes that as long as the FOC at s=0 is negative, the agent wants to hold less than 0. I guess it will break if one considers non-concavities in the value function?
I got rid of the try-except block as @mnwhite suggested.
> Deal with cases when the agent wants to short

- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/ConsumptionSaving/tests/test_ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/distribution.py
In my restoration of the CGMPortfolio remark, I think I've run into a couple of issues with RNG in simulations.
This PR deals with the fact that the random seed now has to be passed to the distribution's _init_ method and not the draw method.
However, my current simulated income paths look like this, which does not seem right
It looks as if there was invididual-level variation in growth rates, but they stayed constant over time?
I'm looking into it but the income distribution RNG is more complicated so I wanted to ask if there is some obvious answer to what is going on there.
> The change in how distributions are handled seems to have messed simulations up

- Documentation/example_notebooks/ConsPortfolioModel.ipynb
- Documentation/example_notebooks/example_ConsPortfolioModel.ipynb
Removes old PortfolioModel docs symlink.
Adds symlink to new PortfolioModel docs notebook.
> Documentation symlink to example_ConsPortfolioModel

- examples/ConsumptionSaving/example_ConsPortfolioModel.py
@llorracc requested minor changes to the example_CPM file regarding the Merton-Samuelson exercise:
- To get rid of the CGM calibration and simply use defaults.
- To have a more informative legend in the plots.
- To use more extreme numbers of discretization points for the risky returns, e.g., 5 vs 200.
This PR introduces those changes.
> Small tweaks to CPM example file

- HARK/ConsumptionSaving/tests/test_ConsPrefShockModel.py
This PR adds a couple checks to the tests of ConsPrefShockModel simulation.
It compares the normalized consumption level with a preset value.
> adding simulation tests on consumption  for ConsPrefShockModel

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsPrefShockModel.py
- HARK/ConsumptionSaving/tests/test_ConsPrefShockModel.py
Addressing a possible issue in ConsPrefShkModel, the seed given to the PrefShkDstn.
This change was recommended by @mnwhite 
This builds on #802, changing the test values.
This is related to work on #803
> fixing seed of PrefShkDstn; changing tests to match

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/tests/test_ConsPrefShockModel.py
- HARK/core.py
> shock_history instead of history namespace for read_shocks

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/ConsLaborModel.py
- HARK/ConsumptionSaving/ConsMarkovModel.py
- HARK/ConsumptionSaving/ConsMedModel.py
- HARK/ConsumptionSaving/ConsPrefShockModel.py
- HARK/ConsumptionSaving/ConsRepAgentModel.py
- HARK/ConsumptionSaving/tests/test_ConsPrefShockModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/core.py
Storing the shock values in a namespace dictionary.
> store shocks in namespace --> #760

- Documentation/example_notebooks/ConsPortfolioModel.ipynb
- Documentation/example_notebooks/GenIncProcessModel.ipynb
- Documentation/example_notebooks/Gentle-Intro-To-HARK.ipynb
- Documentation/example_notebooks/HowWeSolveIndShockConsumerType.ipynb
- Documentation/example_notebooks/IndShockConsumerType.ipynb
- Documentation/example_notebooks/Journey_1_PhD.ipynb
- Documentation/example_notebooks/KinkedRconsumerType.ipynb
- Documentation/example_notebooks/LifecycleModel.ipynb
- Documentation/examples
- Documentation/index.rst
fixes https://github.com/econ-ark/HARK/issues/839
In the revamp I over-rode the manual fix for symlinks in documentation directory, symlinks should be for individual notebooks not the whole examples directory.
> manual symlinks for notebooks as directory symlinks don't work

- .zenodo.json
This should fix the zenodo issues, but we would need to wait till the next release to check this out.
I am still looking for a way to backport this fix to old releases so we have a clean history of releases
available on Zenodo, just like on PyPI.
> apache2.0 is the valid license key for Zenodo not Apache-2.0

- HARK/parallel.py
Fixes https://github.com/econ-ark/HARK/issues/851
The code still contains a "hack" to strip the last two characters `()` from all the methods passed to `multiThreadCommands(Fake)`. Ideally going forward we should only pass in the name of the method in the list of commands. `[solve, initializeSim, simulate]` instead of `[solve(), initializeSim(), simulate()]`.
Should I refactor instances of this in the codebase for the next release or should we wait atleast for a 0.10.8 release.
If we move to `[solve, initializeSim, simulate]` this will break a bunch of REMARKs.
> Use getattr to execute commands instead of exec

- Documentation/example_notebooks/ConsPortfolioModel.ipynb
- Documentation/reference/ConsumptionSaving/ConsIndShockFastModel.rst
- Documentation/reference/ConsumptionSaving/ConsIndShockModelFast.rst
- Documentation/reference/tools/index.rst
- Documentation/reference/tools/solver.rst
- examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.ipynb
- examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.py
Fixes to the documentation.
Clears up some build warnings.
Also, fixes typo in name of "How We Solve" notebook that was preventing it from rendering in RTD.
Should fix #858
> Fixing bugs in documentation

- Documentation/example_notebooks/PerfForesightConsumerType.ipynb
- Documentation/index.rst
- examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.ipynb
- examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.py
- requirements.txt
- setup.cfg
More to fix #858 
This unpins the Sphinx and nbsphinx dependencies in `requirements.txt` which is what RTD is using for its build environment.
On my `sbenthall:sb-docs` branch, the How We Solve notebook is now rendering properly. 
Since we're short staffed and this is an urgent issue, I'll merge it once tests pass.
> docs fixes

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/ConsLaborModel.py
- HARK/ConsumptionSaving/ConsMarkovModel.py
- HARK/ConsumptionSaving/ConsMedModel.py
- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/ConsumptionSaving/ConsPrefShockModel.py
- HARK/ConsumptionSaving/ConsRepAgentModel.py
- HARK/ConsumptionSaving/TractableBufferStockModel.py
- HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
- HARK/core.py
This puts each 'control' variable into a namespace, `controls`, similar to `shocks`.
It does not adjust the storage to use '_now' or '_prev' dictionaries for the controls.
We can discuss this choice in the meeting -- fore example, whether we prefer to put all the 'model variables' including shocks and controls into 'now' and 'prev' dicts.
This is passing tests locally.
> namespace for control variables

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/distribution.py
- HARK/tests/test_distribution.py
- examples/ConsumptionSaving/example_ConsAggShockModel.py
Work from #720 rebased onto `master`. Supersedes #720
> Calc expectation

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/distribution.py
> adds constructor for LogNormal distribution using mean and std

- Documentation/CHANGELOG.md
- HARK/core.py
This PR fixes #493, the issue of AgentCount being undocumented.
It also demonstrates in this one case the way to fix issue #842, which is pervasive across the library.
> makes proper class docstring for AgentType, with AgentCount, fixes #493

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/tests/test_distribution.py
See #639 
This puts a tested MarkovProcess class into distribution for handling sampling from Markov arrays.
The code demonstrates how to turn a general Python function into a numpy function that can broadcast over an array.
It uses the numpy random number generator to sample based on an array of weights instead of coding that up manually with `cumsum` and `searchsorted`.
https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.choice.html?highlight=choice#numpy.random.RandomState.choice
One this is merged in, the next step will be to refactor the Markov model code to use this on the draws.
> MarkovProcess object in distribution.py, towards #639

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/tests/test_distribution.py
This rewrites `calcExpectation` to use `numpy.apply_along_axis`.
It is a _much_ more succinct implementation.
This rewritten version does not compute the tensor product in cases of multiple 1D value inputs.
I have argued in #625 that this should be handled by a different method outside of the `calcExpectation` function.
What this PR lacks in terms of functionality compared to the first implementation, it makes up for in automated tests.
This PR includes tests, including for multivariate distributions with both array and constant non-stochastic values.
> rewrite calcExpectation to use numpy methods, see #625

- HARK/ConsumptionSaving/ConsIndShockModel.py
This pr solves the issues encountered in #899 by implementing model-specific `addStablePoints` functions that can be overwritten in solvers that inherit from `ConsIndShockSolver`.
> Add model-specific addStablePoints()

- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/ConsumptionSaving/tests/test_PerfForesightConsumerType.py
This PR adds tests for the calculation of stable points in the `IndShock` and `PerfForesight` models. The `IndShock` tests use the model from the Buffer stock theory paper.
It fixes a couple of bugs encountered while creating the tests (yay tests):
- `addStablePoints` was in `ConsIndShockSolver` and not `ConsIndShockSolverBasic`, so the points were computed only when cubic interpolation was being used.
- While checking the conditions for existence of stable points in the perfect foresight model, `BoroCnstArt` was treated as a boolean, but it is a float.
> Add tests for "Stable Points"

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/tests/test_ConsAggShockModel.py
- HARK/core.py
Fixes #933.
In the AggShockMarkov and KrusellSmith agents and associated economies, the `MrkvNow` property was being set as an object attribute, despite being a model variable. It's an aggregate property in both cases.
This PR replaces these with a shock `Mrkv`. This is small progress towards #920, which otherwise can be done with simple search-and-replace operations.
`Mrkv` is a shock and not a state in this implementation because the way Market interactions with the Agent currently works, if the Market sets and agent state in its `sow` step, it will be rolled over into the `state_prev` namespace during the simulation in the `cultivate` step. Because here the `Mrkv` state really is exogenous to the agent, `shocks` seems more appropriate, though I hope we can scaffold this a bit better …
> MrkvNow into model state shocks['Mrkv'] in AggShockMarkov and KrusellSmith models

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsAggShockModel.py
- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/ConsMarkovModel.py
- HARK/ConsumptionSaving/ConsMedModel.py
- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/ConsumptionSaving/ConsPrefShockModel.py
- HARK/ConsumptionSaving/ConsRepAgentModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py
Related to #952, fixing a warning message and autodocs around IncShkDstn
> warning message and autodocs around IncShkDstn fixes

- Documentation/CHANGELOG.md
- MANIFEST.in
My recent calibration tools added a couple datasets in csv format to the toolbox.
However, I had no idea these needed to be in the `MANIFEST.in` file to get collected when one installs HARK.
I noticed the issue while messing around with some conda environments for a cluster, and wondering why my tools were not working after installing HARK.
This tiny pr fixes the issue. It is my first time working with `MANIFEST.in`, could someone review?
> Add csv's to MANIFEST.in

- HARK/utilities.py
HARK.utilities.determine_platform() should have been returning, e.g., linux or darwin or windows.  Instead it was returning and extremely detailed string with TMI.  This fixes that.
> utilities.determine_platform() should return, e.g., linux

- Documentation/CHANGELOG.md
- HARK/Calibration/Income/IncomeTools.py
- HARK/Calibration/Income/tests/test_IncomeTools.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py
- examples/Calibration/Sabelhaus_Song_var_profiles.py
I made a grave error with the calibration tools. Sabelhaus & Song's model returns income shock variances, while HARK expects standard deviations. I did not transform the variances and thus, at the moment, shock variances are being interpreted as standard deviations. This can cause income uncertainty to be understated by a factor of 10.
This PR fixes the error. My sincerest apologies for this bug and its timing.
> Fix Sabelhaus-Song variances

- Documentation/CHANGELOG.md
- HARK/dcegm.py
Recent versions of numpy became more strict with respect to data types. Particularly, np.NaN is no longer accepted in integer arrays. This was causing a crash in the DCEGM code whenever it was used with numpy 1.2.0 (which the binder instances do). For instance [the DCEGM DemArk binder link](https://mybinder.org/v2/gh/econ-ark/DemARK/master?filepath=notebooks/DCEGM-Upper-Envelope.ipynb) crashes.
This PR fixes the issue.
> Fix type-related bug in DCEGM

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
- HARK/distribution.py
- HARK/tests/test_distribution.py
This PR introduces a `ConditionalDistribution` class in `distribution.py`
This class represents a distribution that is conditional on some input value. The imaged use case for this includes the age-varying distributions discussed in #1015 and #1017, which are used widely throughout the HARK library.
As a test of integration into the library, I've worked the new class into a couple of the shock computations in the RiskyAsset model.
The current version is tailor to be a replacement of the logic that's currently repeated throughout the model classes: the ConditionalDistribution is configured with lists of values if it represents a "time varying" distribution whose parameters are conditional on an integer index.
Requesting a review from @Mv77
> ConditionalDistribution

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
- HARK/distribution.py
fixes #1003
- [x ] Updated documentation of features that add new functionality.
> use Lognormal.from_mean_std in RiskyAsset forward simulation

- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py
- HARK/tests/test_distribution.py
- requirements.txt
This PR pins the HARK numpy dependency to 1.19.4
This is a version of numpy before recent changes to the random number generator that are causing test failures.
See: https://github.com/econ-ark/HARK/issues/1009#issuecomment-867049221
If tests pass, I recommend merging this. It will prevent other PRs from blocking based on spurious numerical test failures.
Then we can be more deliberate about updating to a more recent numpy and making changes to the tests in an isolated, disciplined way.
> freezing numpy to 1.19.4

- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
Using `calc_expectation` improves solution speed. `test_ConsPortfolioModel.py` runtime:
- w/o `calc_expectation`: 50.05s
- w `calc_expectation`: 27.89s
> [WIP] Use calc_expectation in ConsPortfolioModel

- Documentation/CHANGELOG.md
- HARK/core.py
- HARK/tests/test_core.py
Addresses #994 by making distribute_params use assign_parameters. This ensures that the output of an AgentType matches the real parameter values. Before, if parameters were changed with distribute_params the output would not reflect the changes even though the underlying attribute would be changed. 
- [x ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x ] Updated documentation of features that add new functionality.
- [ x] Update CHANGELOG.md with major/minor changes.
> Distribute_params now uses assign_parameters

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyContribModel.py
My new model did not keep track and properly update start-of-period assets (both risky and risk-free). This PR makes them proper states that get updates throughout simulations.
These entities are not needed to solve the model, but some users might want to record them in simulations and this change makes it easier to do so.
> Track and update start-of-period assets as states in RiskyContrib

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyContribModel.py
This PR moves a function definition of `RiskyContrib` from the main workspace to inside the solver (which is the only place where it is used). It makes the code more readable and results in less parameters being passed around unnecessarily.
@sbenthall does such a small change merit a changelog entry?
> Minor reorganization of RiskyContrib

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
- HARK/core.py
This is PR partially fixes #1022.
It makes the changes for _cyclical_ models only. This involves:
- rotating the input parameters so that the "last" element, which corresponds to the parameters of the 0th period, goes to the 0th place.
- changing the solver to iterate backwards through these elements properly
- using the t'th LivPrb in mortalilty for _this case_.
... it should also involve using t not `t - 1` when drawing shocks but ... we don't seem to have automated tests for a multi-period cyclical case and so they are not failing.
Because this is a pretty complicated change, I'm going to try to fix it for the cyclical cases first and then do the cycles = 1 cases in a separate PR.
> fixing t indexing for inputs for cyclical models

- Documentation/CHANGELOG.md
- HARK/core.py
The line that clears the tracked variables in simulations,
`self.history[var_name] = np.empty((self.T_sim, self.AgentCount)) + np.nan` 
is sometimes producing an annoying warning
`RuntimeWarning: invalid value encountered in add`
The warning is also being printed and not logged and I'm not sure why.
In any case, it seems like a more "pythonic" way to clear/initialize the arrays and one that eliminates the warning is using `np.fill`. That's what this PR does.
> Use .fill(np.nan) when clearing simulation histories

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/tests/test_distribution.py
Fixes a math error in `calc_normal_style_pars_from_lognormal_pars`.
> Fix transformations between normal and lognormal parameters

- HARK/ConsumptionSaving/ConsIndShockModel.py
`aLvl` (`aNrm * pLvl`) is not a state that is required for solving or simulating the models in `ConsIndShockModel`. However, it was determined at some point in history that it was useful to keep track of `aLvl` as if it were a state. This is done for convenience and is mostly used in `ConsAggShockModel`.
See
https://github.com/econ-ark/HARK/blob/a11325ddfc1c403fd91a4120487a955ca30cded0/HARK/ConsumptionSaving/ConsIndShockModel.py#L1845-L1846
However, `aLvl` was never added to the list of state variables https://github.com/econ-ark/HARK/blob/a11325ddfc1c403fd91a4120487a955ca30cded0/HARK/ConsumptionSaving/ConsIndShockModel.py#L1583
This PR adds `aLvl` to the list of states so that `state_now` has the same entries as `state_vars`, which seems desirable to me.
> Add `aLvl` to `state_vars`

- Documentation/CHANGELOG.md
- HARK/distribution.py
The current implementation of `IndexDstn` makes its random-number-generation work slightly different to what the majority of the HARK code currently does. Find the details in the discussion in https://github.com/econ-ark/HARK/pull/1024.
There is no right or wrong way to handle the RNG. Some might prefer what IndexDstn does, others might prefer what the legacy HARK code does. In the end both ways of doing things
a) Represent the same distributions when solving the agents' problems.
b) Draw shocks that follow the same (correct) distributions.
The issue is that the exact value of individual shocks is altered when one tries to replace legacy HARK code with the newer `IndexDstn` tool, and this breaks simulation tests.
This PR changes `IndexDstn` so that the user has the option of creating a …
> IndexDstn rework

- HARK/ConsumptionSaving/ConsIndShockModel.py
My PR https://github.com/econ-ark/HARK/pull/1112 broke some outside functionality (DemARKs and some of @llorracc 's private scripts).
The crux appears to be that `UnempPrbRet` and related parameters can sometimes be `None`. This PR edits the income process constructor to accept that.
> Allow unemp params to be None

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsIndShockModel.py
Pull request for issue:
Newborns' transitory shocks to income #1125
I added an aditional variable: NewbornTransShk which is by default true. If so, Newborn consumers do NOT get a transitory shock in the first period, only a permanent one.
By setting it 'False' Newborn consumers Do get a transitory shock as well.
> 'NewbornTransShk: Option if Newborns get transitory shock'

- Documentation/CHANGELOG.md
- HARK/utilities.py
Simple profiler for HARK models. See #982. 
Example usage: 
```
from HARK.utilities import benchmark
from HARK.ConsumptionSaving.ConsPortfolioModel import PortfolioConsumerType
agent = PortfolioConsumerType(cycles = 0)
benchmark(agent)
```
Output: 
```
Mon Apr 11 19:58:07 2022    restats
2447109 function calls (2232506 primitive calls) in 4.810 seconds
Ordered by: internal time
List reduced from 213 to 10 due to restriction <10>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
12308    1.111    0.000    1.111    0.000 utilities.py:221(CRRAutilityP)
15510    0.771    0.000    0.771    0.000 {method 'searchsorted' of 'numpy.ndarray' objects}
10080    0.539    0.000    1.075    0.000 interpolation.py:798(_evalOrDer)
2715    0.502    0.000    0.786    0.000 …
```
> implement benchmARK

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/tests/test_distribution.py
I noticed a bug in the code that discretizes normal distributions using an equiprobable approximation. This is code that I added some months ago. I was not re-scaling the points from their standardized transformation appropriately.
This PR fixes the issue and adds a test.
I do not think this bug has any major impact:
- Equiprobable is not the default discretization method for the normal distribution.
- The normal distribution is not used much (at all?) around HARK. Most shocks are lognormal.
I'll only have to revise my estimate of my statistical proficiency downward.
> Fix normal equiprobable approximation

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/tests/test_distribution.py
Imagine `x` is a `DiscreteDistribution` object and you want to find the distribution of `f(x)` for some `f`.
This pr introduces a tool called `distr_of_function`. `distr_of_function(x, f)` will return a `DiscreteDistribution` object that represents the distribution of `f(x)`. I wrote tests and made it work for `f: 1->1`, `f: n->1`, `f: 1->n`, and `f: n->m`. You only need `f` to return a `np.array`. 
> Tool to find the distribution of a function of a R.V.

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
This PR allows for interest rate (Rfree) to be "age"-varying in ConsumptionSaving models. 
Currently it is only tested in ConsIndShockModel, but it should work on all other models by design.
> Allows for age-varying interest rate in ConsumptionSaving models

- HARK/econforgeinterp.py
- HARK/tests/test_econforgeinterp.py
This PR adds a simple wrapper for multilinear interpolators from `econforge.interpolation`.
https://github.com/econ-ark/HARK/pull/1136 had some progress on this, but I believe the person in charge is no longer working on HARK. In addition, my simple class works for any dimension (linear, bilinear, trilinear); I've added tests that show how to use it and compare its output with HARK's current classes.
I was careful to also check for `distance metrics`, which might not seem important, but are what determines when to stop when solving an infinite horizon problem. My objects yield the same distance metrics as `LinearInterp` and `BilinearInterp`.
> [WIP] Multilinear wrapper for econforge.interpolation

- HARK/econforgeinterp.py
- requirements.txt
The latest `interpolation.py` release requires irregular grids to be created using `CGrid` and not `UCGrid`, which breaks `LinearFast`.
This fixes the issue.
> Patch LinearFast after interpolation release

- Documentation/CHANGELOG.md
- HARK/distribution.py
I'm starting to use @alanlujan91 's excellent DDL tools.
I noticed a small bug. Some of the discrete distribution features that are extended to DDL expect to be able to access `DDL.seed`. However, the seed is located in `DDL.dataset.seed`; requesting `DDL.seed` returns an error.
This PR fixes the bug by declaring the seed as a property.
Here is an example of code that fails for me without this fix
```
from HARK.distribution import DiscreteDistributionLabeled
import numpy as np
my_dstn = DiscreteDistributionLabeled(
pmv = np.array([0.5,0.5]),
data = np.array([-1,1]),
var_names = ['my_var']
)
my_dstn.dataset
sq_dstn = my_dstn.dist_of_func(lambda x: x['my_var']**2)
sq_dstn.atoms
```
> Add seed as property of DiscreteDstnLabeled

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/tests/test_distribution.py
Augments the existing `combine_indep_dstns` to take and use labeled distributions. If all the inputs are of the class `DiscreteDistributionLabeled`, the result will be another labeled discrete distribution with the labels of the variables in the original distributions.
Addresses https://github.com/econ-ark/HARK/issues/1190
> Combine labeled distributions

- HARK/ConsumptionSaving/ConsIndShockModel.py
Addresses #596
Removes `IndShockConsumerType.Ex_Mtp1_over_Ex_Ptp1` and `IndShockConsumerType.Ex_mtp1`
This code crashes when executed and is neither documented nor up to style standards.
> removing unused old Mtp1 code, fixes #596

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
- HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
Our current implementation of models with risky returns impose the restriction that, when simulating, a single economy-wide return is drawn every period.
This PR adds the option for the returns that are drawn in simulation to be agent-specific.
This is useful, for instance, if you are doing a monte-carlo simulation to find the average consumption at age 45 implied by your model. With the current restriction, there is some inefficiency in the fact that agents' lives are correlated through return draws. Drawing a different shock for every agent breaks this correlation, and (I think?) increases the efficiency of the estimator (for a given `AgentCount` and `T_sim`).
> Allow risky return draws to be agent-specific.

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
- HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
The PR with idiosyncratic risky return draws (https://github.com/econ-ark/HARK/pull/1250) had a typo: `riksy` instead of `risky`.
This PR fixes the typo
> Fix typo in recently merged PR

- .codecov.yml
- HARK/mat_methods.py
- HARK/tests/test_mat_methods.py
The transition-matrix way of doing things involves spreading the mass of simulated points to an exogenous grid of the state space. We currently can do this for 1D and 2D state spaces with the `jump_to_grid_1D` and `jump_to_grid_2D` methods. This PR adds a method called `mass_to_grid`, which achieves the same goal, but for ND state spaces.
It adds tests that verify that the output of the new function is the same as that of `jump_to_grid_1D` and `jump_to_grid_2D` . In my own tests, `mass_to_grid` is about ~2 times slower than the `jump_to_grid_1D` and `jump_to_grid_2D` methods. Still, I thought it would be good to have the general version around at least for testing higher-dimensional models. If performance ever becomes an issue we can try to make it faster, or code up `jump_to_grid_3D`. …
> N-dimensional 'jump_to_grid'

- Documentation/CHANGELOG.md
- HARK/metric.py
- HARK/tests/test_core.py
There is a bug in the distance metric for dictionaries.
This PR fixes it and adds a test.
> [BugFix] Dictionary metric

- .github/workflows/coverage.yml
- .github/workflows/examples.yml
- .github/workflows/hark.yml
The main CI takes a long time; skip it for documentation-only changes.
A
> Skip CI for documentation-only PRs

- .github/workflows/documentation.yml
This should speed up the CI by performing fewer downloads on each CI run.
A
> Cache PyPI packages in the documentation workflow

- Documentation/contributing/Installation_instruction.md
This fixes a syntax error in the parser: ``Documentation\contributing\Installation_instruction.md:0: ERROR: Document may not end with a transition.``
A
> Remove transition from the end of ``Installation_instruction.md``

- Documentation/conf.py
This PR sets the Econ-ARK logo to the favicon of the page in the documentation. A more ideal favicon might be the four lines isolated, maybe enlargened a bit, and put into a square aspect ratio -- but we mustn't let perfect be the enemy of the good!
A
cc: @MridulS
> Adopt favicon

- Documentation/conf.py
cc: @MridulS @DominicWC
This PR adds 'icon links' to the top-right of the header, for quick access to various Econ-ARK related things, similar to e.g. [NumPy's](https://numpy.org/doc/stable/) documentation.
A
> Add icons-links to the documentation header

- .github/workflows/documentation.yml
- Documentation/conf.py
- Documentation/index.rst
- pyproject.toml
- requirements/dev.txt
- requirements/doc.txt
cc: @MridulS @DominicWC
This PR is on top of #1313, and adds a landing-page grid of links, similar to SciPy, NumPy, MatPlotLib, et al.
Open to suggestions about the order and content of the four boxes, I've chosen what I think is a sensible starting point.
A
> Add a grid of links to the landing page

- Documentation/conf.py
> add edit buttons in docs

- .github/workflows/documentation.yml
cc: @MridulS
This adds automatic linting checks to the documentation, to run on every PR.
Due to the symlink, ``GenIncProcessModel`` needs to be excluded for now.
A
> Add ``sphinx-lint`` checks to CI

- .github/workflows/documentation.yml
cc: @MridulS
Given ``numba`` now supports Python 3.11 I tried to increase all the way, but ``interpolation`` has an upper-limit on Python 3.10 -- see https://github.com/EconForge/interpolation.py/issues/103 and https://github.com/EconForge/interpolation.py/pull/105.
A
> Use Python 3.10 in the documentation workflow

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
- HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
I was getting errors trying to get `ConsPortfolio` to use time varying interest rates `Rfree`.
The culprit was that the share-limit calculation assumed `Rfree` is constant. This PR fixes the issue.
> Let `ConsRiskyAssetModel` handle time-varying Rfree

- examples/ConsIndShockModel/PerfForesightConsumerType.ipynb
- Replaced the `\texttt{}` LaTeX environment with standard markdown code in the perfect foresight notebook
CC: @llorracc @alanlujan91
> Replace \texttt{} in notebooks

- .github/workflows/documentation.yml
- Documentation/CHANGELOG.md
- HARK/__init__.py
- pyproject.toml
- requirements/base.txt
Update CHANGELOG, init, pyproject.
> Preparation for v0.14.0 release

- HARK/tests/test_HARKutilities.py
- HARK/utilities.py
Metadata argument was not supported for this filetype, was throwing error. CDC wants a minor release for this. I'm going to put in one more annoying behavior fix before I do that.
> Remove metadata argument for jpg in make_figs

- Documentation/CHANGELOG.md
- HARK/econforgeinterp.py
The `CGrid` constructor of the econforge interpolation library can take a substantial time if you build many interpolators.
This PR allows you to pass a pre-constructed `CGrid` object to `LinearFast`.
This can save a lot of time in instances where you are building many interpolators over the same grid. For example, if you have consumption functions for many Markov states that are defined over the same asset grid. (cc: @wdu9 ?)
> Allow for a pre-built grid in `LinearFast`

- HARK/ConsumptionSaving/ConsBequestModel.py
- HARK/ConsumptionSaving/ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
- HARK/ConsumptionSaving/tests/test_ConsBequestModel.py
- HARK/ConsumptionSaving/tests/test_ConsGenIncProcessModel.py
- HARK/ConsumptionSaving/tests/test_ConsMedModel.py
- HARK/ConsumptionSaving/tests/test_ConsRiskyAssetModel.py
- HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
This PR *only* adds new tests (and makes tiny adjustments to old ones) for consumption-saving models and should be merged *before* my solvers overhaul branch. But not yet because I'm actively adding tests.
> Add more consumption-saving tests

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsMarkovModel.py
- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
Through a combination of math and experimentation, I've found the correct computation of "human wealth" in the presence of risky returns. I've implemented it for RiskyAssetModel and FixedShareModel. On the next commit I'll get it working for the PortfolioChoice models, and then turn to ConsMarkovModel.
The good news is that I have the right answer. The bad news is that (other than partly getting to it via whiteboard math and following some clues from experimentation) I don't have a proof of *why* it's correct. I'll write it up in a short file and circulate.
This PR will also fix a very small mistake in the computation of hNrm by calc_limiting_values; that code uses an alternate definition of hNrm that will be off by exactly 1.
> Correct human wealth with risky returns

- Documentation/CHANGELOG.md
- HARK/model.py
- HARK/models/fisher.py
- HARK/models/perfect_foresight.py
- HARK/models/perfect_foresight_normalized.py
- HARK/models/test_models.py
- HARK/simulation/monte_carlo.py
- HARK/simulation/test_monte_carlo.py
- HARK/tests/test_model.py
- examples/MonteCarlo/Generic Monte Carlo Perfect Foresight.ipynb
This separates out the calibration data from the dynamics in the DBlock
> move calibration out of DBlock definition, see #1371

- HARK/tests/test_econforgeinterp.py
- requirements/base.txt
The EconForge interpolation tests are failing, but nothing in our code has changed. As of right now, this branch only exists to demonstrate the problem: The latest commit on the master branch passed its tests, but now a new branch with only a trivial change (adding a period to a comment) fails them.
This branch *will* be used to fix the tests once we know what's going on.
> Fix EconForge interpolation tests [WIP]

- Documentation/CHANGELOG.md
- HARK/model.py
- HARK/tests/test_model.py
Introduces `discretize` methods for blocks, which apply the discretization parameters to the shocks.
In the RBlock case, this is done recursively.
The point of this is to provide an API which a user can call to modify the 'true' version of a model into a discretized one.
The discretized model can then be used for solution and simulation.
(in the future, a YAML configuration will interact with this API)
> discretize() methods for blocks

- Documentation/CHANGELOG.md
- HARK/ConsumptionSaving/ConsIndShockModel.py
Two lines that were added to the income process of consindshock for `cstwMPC` are now causing trouble. See https://github.com/econ-ark/HARK/issues/984 and https://github.com/econ-ark/HARK/issues/1182.
This PR removes those lines. This does not break anything _within_ HARK itself.
> Remove employment accounting lines

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/model.py
- HARK/models/consumer.py
- HARK/simulation/monte_carlo.py
- HARK/tests/test_model.py
The "new model files" have had a problem, which is that they depend on fully constructed Distribution objects for each shock. That meant that things like, for example, the standard deviation of the transitory shock could not depend on a calibration dictionary passed in at simulation (let alone solution) time.
This PR fixes this issue.
Now, model files can define shocks with a tuple, e.g. `(Lognormal, {"mean": "Rfree + EqP", "std": "RiskyStd"})`.
When the Monte Carlo simulator is initialized with a calibration dictionary containing values for `Rfree`, `EqP`, and `RiskyStd`, the expressions in the strings are evaluated in the scope of calibration, and these values are passed through to the constructor for `Lognormal`.
Note that since we presume that the shocks are truly exogenous, these …
> Construct shocks with mathematical expression arguments using calibration scope

- Documentation/CHANGELOG.md
- HARK/distribution.py
- HARK/model.py
- HARK/models/consumer.py
- HARK/models/consumer.yaml
- HARK/parser.py
- HARK/simulation/monte_carlo.py
- HARK/tests/test_model.py
- HARK/tests/test_parser.py
- requirements/base.txt
This PR aims to provide a YAML configuration file for the blocks for the normalized consumer problem as well as the portfolio choice extension. It is work towards #1373 
It also aims to provide a working parser, which can produce well-formed block objects that are compatible with the Monte Carlo simulator.
This PR builds on #1464
> YAML configuration for consumer portfolio problem, with parser and working tests.

- Documentation/CHANGELOG.md
- HARK/Calibration/Income/IncomeProcesses.py
Per meeting on 8/14, CDC wants users to be able to specify idiosyncratic permanent income growth rather than overall permanent income growth. This commit adds a constructor method that combines PermGroFacAgg and PermGroFacInd to make PermGroFac. Someone using it would simply put their idiosyncratic growth information in PermGroFacInd instead of PermGroFac; when they change PermGroFacAgg, just run ThisType.construct('PermGroFac') and it will adjust.
> Add ind-agg PermGroFac constructor function

- HARK/ConsumptionSaving/ConsWealthPortfolioModel.py
Updated this AgentType subclass to use constructors, have standalone default dictionary. Still has no tests nor documentation.
This fix is needed for the TRP estimation project to work correctly.
> WealthPortfolioConsumerType uses constructors

- HARK/distributions/__init__.py
- HARK/distributions/utils.py
- HARK/tests/test_distribution.py
Qingyuan: I closed Pull requests #1409 and initiate this new one. 
> Add an alternative way of implementing Tauchen's method to make_tauchen_ar1()

- Documentation/CHANGELOG.md
- HARK/core.py
- HARK/tests/test_core.py
Sometimes (e.g. when using the Fake News method to get Jacobians), it is useful to solve a model backwards starting from a solution object that one already has in hand.
For instance, imagine an infinite horizon model. I have already computed the steady state solution `ss_sol`. Now I want to know what the solution would be if I gave the model the sequence of inputs `[R_ss, R_ss, R_ss + dx, R_ss, R_ss, ...]`. I can solve my problem by doing backward induction on a three-period model with inputs `[R_ss, R_ss, R_ss + dx]` that takes `ss_sol` as its continuation value/ terminal solution.
This PR adds exactly this functionality, which I have had in my private branches for a while and has been very useful.
I imagine you can somehow already do this in HARK, manually overriding …
> Start solver from arbitrary solution object

- HARK/ConsumptionSaving/ConsMarkovModel.py
- HARK/ConsumptionSaving/ConsPortfolioModel.py
- HARK/ConsumptionSaving/ConsRiskyAssetModel.py
In building the new simulator system, I caught several mistakes in the current system:
- MrkvPrbsInit was missing from default dictionary
- unused definition of J in Markov sim code
- Mrkv wasn't properly accessible in history
- controls were broken when AdjustPrb < 1.0
- Rport was being set as if Share=1 no matter what
This PR fixes those issues.
> Small fixes to simulator methods

- HARK/distributions/utils.py
- correct typo in `make_markov_approx_to_normal_by_monte_carlo`
- `python -m compileall -q HARK/distributions/utils.py`
- `pytest -k utils -q` *(fails: command not found)*
> Fix Monte Carlo distribution assertion

- HARK/core.py
- reference `initialize_sim()` in error string
- `pip install -e .[dev]` *(fails: Could not find a version that satisfies the requirement setuptools>=61.2)*
> Fix typo in core error message

- HARK/simulation/test_monte_carlo.py
- refactor Monte Carlo tests to use `numpy.testing.assert_allclose`
- `pytest --version` *(fails: No module named pytest)*
- `pip install numpy` *(fails: cannot connect to proxy)*
> Use assert_allclose in tests

- HARK/core.py
- allow parallel execution in `AgentPopulation.simulate`
- set a flag to warn only once if parallel execution fails
- replace variable docstring with a comment
- `python -m pytest -n auto`
> Enable parallel simulation for AgentPopulation

- HARK/ConsumptionSaving/ConsIndShockModel.py
- HARK/core.py
- HARK/utilities.py
- vectorize kernel regression computations
- streamline epanechnikov kernel
- use numpy indexing to get interest rates
- evaluate polynomials with `np.polyval`
- eliminate loops in idiosyncratic-shock consumer functions
- use boolean arrays directly in `core.AgentType`
- `ruff check --fix HARK/core.py HARK/ConsumptionSaving/ConsIndShockModel.py`
- `pytest -n auto` *(fails: KeyboardInterrupt)*
> Improve numpy usage

- HARK/models/test_models.py
This small PR removes the duplicated `test_pfnm` in `HARK/models/test_models.py` which contains the same logic.
> Remove duplicated pfnm test

- .ragignore
- config/rag_config.yaml
- rag_config.yaml
This PR adds a .ragignore file to configure the repository for optimal AI/RAG system indexing.
- Defines source file priority (markdown, notebooks, Python code)
- Specifies files to ignore (generated, temporary, binary files)  
- Sets up master file relationships
- Configures careful processing rules for different file types
- Improves search quality for AI tools
- Reduces index size by excluding irrelevant files
- Prioritizes source files over generated content
- Enables better AI-powered code analysis
This is part of the Econ-ARK AI-friendly repository initiative.
> Add .ragignore for AI-friendly repository indexing

- HARK/ConsumptionSaving/ConsIndShockModel.py
- tests/ConsumptionSaving/test_ConsNewKeynesianModel.py
- tests/ConsumptionSaving/test_IndShockConsumerType.py
- tests/ConsumptionSaving/test_modelcomparisons.py
This feature wasn't ready for primetime and is causing bad numeric behavior with vFuncBool. Test targets have been reverted.
> Turn off use_infimum

- docs/guides/index.rst
- docs/guides/krusell_smith.md
Introduces a comprehensive guide for the Krusell-Smith (1998) heterogeneous agent macroeconomic model in HARK, including usage examples, model components, solution algorithm, related models, best practices, and references. The guide is added as docs/guides/krusell_smith.md and linked from the guides index.
> Add Krusell-Smith model guide to documentation
